### ISSUE TITLE
Uploading to password protected room not possible

### ISSUE THREAD

**Issue by nickhero** [RealDolos/node-volaupload#1]
Hey, thank you at first for redirecting me here from your python volaupload.
This tool works flawlessly for rooms with no room-password. Once i try to upload to a protected room gives me the following errors everytime: (On debian 9 stretch with node v10.10.0 and npm 6.4.1 - but i also tried it on Windows 10 with the same versions)

> volaupload -r MyRoomName -u 'MyUser' -p 'MyPassword' -a 'MyRoomPassword' FILE 'test.zip'

(Obviously with the right values filled in, doh)

```node
{ Error: ENOENT: no such file or directory, stat 'FILE'
    at Object.statSync (fs.js:829:3)
    at collect_files (/usr/lib/node_modules/volaupload/upload.js:39:23)
    at collect_files.next (<anonymous>)
    at Function.from (<anonymous>)
    at main (/usr/lib/node_modules/volaupload/upload.js:176:17)
    at Object.<anonymous> (/usr/lib/node_modules/volaupload/upload.js:249:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12) errno: -2, syscall: 'stat', code: 'ENOENT', path: 'FILE' }
Ignored FILE: No files matched
Deploying one botnet payload to 1 rooms
Greenfagging in as MyUser
Connecting to mainframe cluster https://volafile.org/r/MyRoomName
test.zip [#################################################################] 100.0%   4.46M/4.46M dl5  4.34M/s   1.0s
Failed to upload test.zip: Upload failed! <html><head></head><body><script type="text/javascript">if(window.frameElement && typeof(window.frameElement.haveFinished) === 'function'){
    window.frameElement.haveFinished(
      false,
      "An error occured",
      403);
}</script>&quot;An error occured&quot;</body></html> (Attempt 1)
```

Anyways, hope this helped and thanks for your work with the tool.

**Comment by ghost** [comment]
Don't write FILE in your command line, just the path to your file

```shell
volaupload -r https://volafile.org/r/pvn3bbe4 -a roompassword -u username -p userpasswd /path/to/your/file.ext
```

works fine
